server:
  port: 9191
spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active:
      - prod
  application:
    name: EES-MS-ACCOUNTING
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.sql: DEBUG

info:
  app:
    name: Secure Platform Enexse Intranet TimeSheets Microservice
    version: 1.0
    description: CRUD TimeSheets | Solutions | Profiles | Activities Microservice

swagger:
  enable: true


