apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: ees-ms-accounting-app
  labels:
    app: ees-ms-accounting-app
spec:
  selector:
    matchLabels:
      app: ees-ms-accounting-app
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: ees-ms-accounting-app
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: eureka-cm
                key: postgres_db
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: eureka-cm
                key: postgres_host
          - name: POSTGRES_PORT
            valueFrom:
              configMapKeyRef:
                name: eureka-cm
                key: postgres_port
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: eureka-cmmes
                key: postgres_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: eureka-cm
                key: postgres_password
      - name: ees-ms-accounting-app
        image: enexse/ees-ms-accounting:latest # Image that will be used to containers in the cluster
        args: ["--spring.profiles.active=prod"]
        imagePullPolicy: Always
        ports:
        - containerPort: 9191 # The port that the container is running on in the cluster
        env:
          - name: POSTGRES_URL
            valueFrom:
              configMapKeyRef:
                name: eureka-cm
                key: postgres_url
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: eureka-cm
                key: postgres_user
          - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: postgres_password
          - name: EUREKA_SERVER_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: eureka-cm
                key: eureka_service_address
          - name: KEYCLOAK_REALM
            valueFrom:
              configMapKeyRef:
                name: eureka-cm
                key: keycloak_realm
          - name: KEYCLOAK_AUTH_SERVER_URL
            valueFrom:
              configMapKeyRef:
                name: eureka-cm
                key: keycloak_auth_server_url
          - name: KEYCLOAK_RESOURCE
            valueFrom:
              configMapKeyRef:
                name: eureka-cm
                key: keycloak_resource
          - name: KEYCLOAK_CREDENTIALS_SECRET
            valueFrom:
              configMapKeyRef:
                name: eureka-cm
                key: keycloack_credentials_secret

---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata:
  name: ees-ms-accounting-svc # Metadata of the resource kind we are creating
spec:
  selector:
    app: ees-ms-accounting-app
  ports:
    - port: 80 # The port that the service is running on in the cluster
      protocol: TCP
      targetPort: 9191 # The port exposed by the service
  type: ClusterIP # type of the service.

