apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: ees-ms-accounting-app
  labels:
    app: ees-ms-accounting-app
spec:
  selector:
    matchLabels:
      app: ees-ms-accounting-app
  template:
    metadata:
      labels:
        app: ees-ms-accounting-app
    spec:
      containers:
      - name: ees-ms-accounting-app
        image: enexse/ees-ms-accounting-app:latest # Image that will be used to containers in the cluster
        imagePullPolicy: Always
        ports:
        - containerPort: 9191 # The port that the container is running on in the cluster

---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata:
  name: ees-ms-accounting-svc # Metadata of the resource kind we are creating
spec:
  selector:
    app: ees-ms-accounting-app
  ports:
    - port: 80 # The port that the service is running on in the cluster
      protocol: TCP
      targetPort: 9191 # The port exposed by the service
  type: ClusterIP # type of the service.
